### ISSUE TITLE
Document what each issue label means in the TPB wiki

### ISSUE THREAD

**Issue by shanek21** [chauncy-crib/tagprobot#116]
I have no idea anymore. Everything is an enhancement.

**Comment by davidabrahams** [comment]
Leaving this as a reference for what we could change our labels to:

https://github.com/jvandemo/github-scrum-workflow

**Comment by shanek21** [comment]
Link to page about issues on our wiki:
https://github.com/chauncy-crib/tagprobot/wiki/Agile-Workflow

**Comment by davidabrahams** [comment]
I think we're good here, and can close this issue.
