### ISSUE TITLE
Improve tileInfo code

### ISSUE THREAD

**Issue by billmwong** [chauncy-crib/tagprobot#129]
The way the current code is laid out makes the tile file setup code not super readable and makes the tests have to mock things that maybe shouldn't have to be.

 - I mostly don't like having to call the setupTiles function in map.spec to mock the tileinfo.  This should be refactored to rewire the stuff in map.js, not tiles.js.  Maybe refactoring the code will make this unnecessary.

**Comment by davidabrahams** [comment]
Agreed on this idea. Shouldn't be too bad to mock the info in map.js. Might be able to get to this this sprint.

Also adding the unit-test label
