### ISSUE TITLE
Research navigational mesh algorithm

### ISSUE THREAD

**Issue by shanek21** [chauncy-crib/tagprobot#201]
- Understand nav mesh algorithm

**Comment by billmwong** [comment]
Writing down resources here for reference
- The bible: http://jceipek.com/Olin-Coding-Tutorials/pathing.html
- Quadtrees
- Convex polygon generator: http://www.critterai.org/projects/nmgen_study/polygen.html
- Nav mesh with medial axis paper: https://www.staff.science.uu.nl/~gerae101/UU_crowd_simulation_publications_dynamic_navigation_mesh.html
- Meadow map paper: https://www.cc.gatech.edu/ai/robot-lab/online-publications/ieee/path86.pdf
- Local multiresolution path planning paper: https://www.ais.uni-bonn.de/nimbro/papers/HSR10_Steffens.pdf

**Comment by billmwong** [comment]
I like Local Clearance Triangulation (LCT) the best, as described in this paper: http://graphics.ucmerced.edu/papers/14-tog-lct.pdf

I has some advantages over Explicit Corridor Maps (ECM) in that it can be generated faster, the math is simpler, and it requires less graph nodes.  It seems to be able to do all the same things we want--namely quick dynamic updates, quick clearance calculations, and corridor output.
