### ISSUE TITLE
Implement Dynamic Triangulation Updates

### ISSUE THREAD

**Issue by shanek21** [chauncy-crib/tagprobot#206]
Handle changing map
unit tests

**Comment by billmwong** [comment]
Handle changing map possibility: http://www.staff.science.uu.nl/~gerae101/pdf/CAVW_Dynamic_ECM.pdf

**Comment by davidabrahams** [comment]
https://hal.inria.fr/inria-00560379/file/paper.pdf

Section 2.2 has good alg

**Comment by davidabrahams** [comment]
https://hal.inria.fr/inria-00167201/file/hal.pdf

Another paper
