### ISSUE TITLE
Improve defense

### ISSUE THREAD

**Issue by shanek21** [chauncy-crib/tagprobot#241]
Come up with list of scenarios that we want our bot to handle and high-level proposal of how to use the info we have to set our own target

Possible scenarios to think about:
- Sit on the flag
- Sit between enemy and flag
- Handle bombs/boosts in the area
- If an enemy has a powerup

**Comment by billmwong** [comment]
https://docs.google.com/document/d/1UeeIrINfZSyP9KXlwFd4LVIcpTpdksgjji3VfzpGal0/edit
