### ISSUE TITLE
Treat dummy points symbollically in triangulation algorithm

### ISSUE THREAD

**Issue by davidabrahams** [chauncy-crib/tagprobot#245]
Right now, we hard code values that work for Command Center. They won't work for other maps (but the code will assertion error if the points are incorrect, so we'll know the points are in the wrong spot.)

**Comment by billmwong** [comment]
David and Shane have both independently tried this without much success and our current 3-dummy-point system implemented in #285 works for all maps.  @davidabrahams can I close this?

**Comment by davidabrahams** [comment]
Ya! Closingggg
