### ISSUE TITLE
Stop compiling to `public/test.js`

### ISSUE THREAD

**Issue by davidabrahams** [chauncy-crib/tagprobot#26]
Running `npm run build:test` in `scalable-grid-size` creates this file

**Comment by davidabrahams** [comment]
This issue exists on `master` too

**Comment by billmwong** [comment]
I can't believe you've done this

**Comment by davidabrahams** [comment]
Okay so I'm not sure if there's a clean way to resolve this while still running tests using `npm run build:test`. The solution for now will just be to gitignore the file. See PR #42 for this info
