### ISSUE TITLE
The starting cell on our Cell A* is up and to the left of our ball

### ISSUE THREAD

**Issue by davidabrahams** [chauncy-crib/tagprobot#265]
I put the path drawing in the foreground and made it opaque to show this. Here's a screenshot.

![Screenshot from 2017-11-08 00-33-17.png](https://images.zenhubusercontent.com/5963a1ca61b4ca3b0a73de45/14f535c4-e9af-40b4-961f-37f7d03be448)

**Comment by billmwong** [comment]
Obsolete because we use funnel now
