### ISSUE TITLE
Visualize Planned Path

### ISSUE THREAD

**Issue by altodyte** [chauncy-crib/tagprobot#32]
See what can be learned from extant TagPro enhancements to visualize the planned path of the TagProBot.

Extant enhancements for reference:
https://gist.github.com/chrahunt/954b0a4510df9fe71698
https://www.reddit.com/r/TagPro/comments/3cfq6v/userscript_little_helper_to_show_bomb_guides_ball/

**Comment by davidabrahams** [comment]
Closes #32 and #38
