### ISSUE TITLE
Split `updateAndRedrawEntireNavmesh` into two functions

### ISSUE THREAD

**Issue by shanek21** [chauncy-crib/tagprobot#334]
I'm realizing now maybe having functions with the word And in should be avoided? Like, maybe we should have an updateNavMesh function which does all of this function except the last line. It could then return if a tile changed (or we could store in a global). Then we could call if (tileChanged) redrawNavMesh().

**Comment by davidabrahams** [comment]
In reference to `updateAndRedrawEntireNavmesh`

**Comment by billmwong** [comment]
Done
