### ISSUE TITLE
Get rid of getPixiSquare()

### ISSUE THREAD

**Issue by billmwong** [chauncy-crib/tagprobot#338]
Instead, just use default parameters and call `getPixiRect(xp, yp, size, alpha, color, width, width = height)`

**Comment by scope-fidelity-circleci** [comment]
Ammendment: `getPixiRect(xp, yp, size, alpha, color, width, height = width)`

**Comment by davidabrahams** [comment]
Ammendment: `getPixiRect(xp, yp, size, alpha, color, width, height = width)`
