### ISSUE TITLE
Unify function comments

### ISSUE THREAD

**Issue by shanek21** [chauncy-crib/tagprobot#44]
Possible convention:
```
/*
 * General overview of function, making sure to mention, in English,
 * the return value (if it exists). Example inputs / outputs (if
 * complicated/confusing enough of a function):
 *
 * @param a: description of a
 * @param b: description of b
 *
 * @return: description of return value
 */
function example(a, b) {

}
```
Now accepting other convention nominations!

**Comment by davidabrahams** [comment]
there's a little guidance given (here)[https://github.com/airbnb/javascript#comments], but not much. I like this convention, and I agree we should slowly transition toward at least some convention... @altodyte @billmwong thoughts?

**Comment by billmwong** [comment]
I'm personally a fan of trying to write your code and name your variables/functions such that someone can understand it intuitively.

That being said, sometimes you need comments and a convention is good.  I don't think every function needs a docstring with all of the above things though

**Comment by davidabrahams** [comment]
Hm. that's a good point. I think one thing is that perhaps we don't want to expect eachother to actually understand all the code inside a function. Like, if you write a really complicated function, but you clearly define the inputs and outputs of that function in the docstring, then someone else can use that function w/o ever having to look at your code. This might be advantageous in the future to speed up development.

@shanek21 I reread your template and my one comment is that I don't think its necessary to have an `@return` if in the docstring we explain what the function returns.

Thoughts?

**Comment by shanek21** [comment]
If there is one place I like redundancy in my code, it's the documentation.
