### ISSUE TITLE
Make usage of the word "grid" consistent.

### ISSUE THREAD

**Issue by davidabrahams** [chauncy-crib/tagprobot#49]
Per review in #23 , we should make "grid" synonymous with "2d array". If at any point we use it to mean something more specific, we need to change our terminology so its clear what "grid" means in that situation.

@altodyte let me know if this is an appropriate treatment of this issue

**Comment by altodyte** [comment]
> grid: the grid of tiles that makes up the map.
This is in the summary for #23 
I'm fine with grid === 2d array, but would recommend adding it to the README, which should probably mature into a wiki at this point.

**Comment by davidabrahams** [comment]
I added a definition to the wiki. I looked through the code, and we're using the term properly. closing this!
