### ISSUE TITLE
Fix the `convolve` function and its helper functions such that they allow non-square kernels

### ISSUE THREAD

**Issue by shanek21** [chauncy-crib/tagprobot#88]

**Comment by davidabrahams** [comment]
coolio! this seems very low priority since i don't see us actually needing to do this. but also i think all you have to do is remove the assert and it works?

**Comment by shanek21** [comment]
It's slightly more intensive than that, but that only further pushes it down our ToDo list :izakaya_lantern: :dango: :calendar: :date: :diamond_shape_with_a_dot_inside:

**Comment by davidabrahams** [comment]
love low priority tasks

**Comment by davidabrahams** [comment]
Given that all kernels are completely removed from codebase at this point, I'm closing this card.
